config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  resources :tools
  resources :users, only: [:new, :create, :index]
  get  '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: "sessions#destroy"
end

app/models/tool.rb
class Tool < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by( username: params[:session][:username] )
    if user && user.authenticate( params[:session][:password] )
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash.now[:error] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end
end

app/controllers/tools_controller.rb
class ToolsController < ApplicationController
  def index
    @tools = Tool.all
  end

  def show
    @tool = Tool.find(params[:id])
  end

  def new
    @tool = Tool.new
  end

  def create
    @tool = Tool.new(tool_params)
    if @tool.save
      redirect_to tool_path(@tool)
    else
      render :new
    end
  end

  def edit
    @tool = Tool.find(params[:id])
  end

  def update
    @tool = Tool.find(params[:id])
    if @tool.update(tool_params)
      redirect_to tool_path(@tool)
    else
      render :edit
    end
  end

  def destroy
    @tool = Tool.find(params[:id])
    @tool.destroy
    redirect_to tools_path
  end

  private

  def tool_params
    params.require(:tool).permit(:name, :price, :quantity)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new( user_params )
    if @user.save
      redirect_to users_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome to Tool Chest</h1>
<%= link_to "Checkout Some Tools", tools_path %>
<br>
<%= link_to "Sign In", login_path %>
<%= link_to "Create Account", new_user_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ToolChest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tools/edit.html.erb
<%= form_for(@tool) do |form| %>
  <%= form.label :name %><br>
  <%= form.text_field :name %><br>
  <%= form.label :price %><br>
  <%= form.text_field :price %><br>
  <%= form.label :quantity %><br>
  <%= form.text_field :quantity %><br>
  <%= form.submit %>
<% end %>

app/views/tools/index.html.erb
<%= link_to "New tool", new_tool_path %><br><br>

<% @tools.each do |tool| %>
  <%= link_to tool.name, tool_path(tool) %><br>
<% end %>

app/views/tools/new.html.erb
<%= form_for(@tool) do |form| %>
  <%= form.label :name %><br>
  <%= form.text_field :name %><br>
  <%= form.label :price %><br>
  <%= form.text_field :price %><br>
  <%= form.label :quantity %><br>
  <%= form.text_field :quantity %><br>
  <%= form.submit %>
<% end %>

app/views/tools/show.html.erb
<h1> <%= @tool.name %> - <%= @tool.quantity %> </h1>
<h3> <%= @tool.price %> </h3>
<%= link_to "Edit tool", edit_tool_path(@tool) %><br>
<%= link_to "DESTROY", tool_path(@tool), method: :delete %>

app/views/users/index.html.erb
<h1>Users</h1>

<% @users.each do |user| %>
Welcome, <%= user.username %>!
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.submit "Create Account" %>
  <% end %>